/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#3b82f6",
        "on-tertiary-container": "#3b82f6",
        "error": "#ef4444",
        "on-primary-container": "#cbd5e1",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#1c222b",
        "on-surface-variant": "#94a3b8",
        "surface-container": "#13181f",
        "surface-bright": "#13181f",
        "on-secondary-fixed": "#ffffff",
        "tertiary-fixed": "#3b82f6",
        "on-primary-fixed": "#ffffff",
        "inverse-on-surface": "#0f172a",
        "on-secondary-container": "#00C853",
        "inverse-surface": "#f1f5f9",
        "surface-container-lowest": "#0b0e12",
        "secondary": "#00C853",
        "on-tertiary-fixed-variant": "#ffffff",
        "secondary-fixed": "#00C853",
        "secondary-fixed-dim": "#00a344",
        "primary-fixed": "#1c385f",
        "surface-tint": "#1c385f",
        "error-container": "#ef44441a",
        "tertiary-fixed-dim": "#2563eb",
        "surface-container-low": "#0f141a",
        "surface-container-highest": "#252c38",
        "outline": "#1e293b",
        "on-error-container": "#ef4444",
        "surface-dim": "#0d1117",
        "on-secondary": "#ffffff",
        "primary": "#1c385f",
        "on-primary-fixed-variant": "#94a3b8",
        "primary-fixed-dim": "#152a47",
        "primary-container": "#1c385f66",
        "on-background": "#f1f5f9",
        "surface-variant": "#1c222b",
        "inverse-primary": "#334155",
        "on-tertiary-fixed": "#ffffff",
        "on-surface": "#f1f5f9",
        "outline-variant": "#334155",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#ffffff",
        "tertiary-container": "#3b82f61a",
        "surface": "#0f141a",
        "secondary-container": "#00C8531a",
        "background": "#13181f",
        "accent-green": "#00C853",
        "background-light": "#f6f7f8",
        "background-dark": "#13181f",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "display": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
